### ISSUE TITLE
Play video from youtube

### ISSUE THREAD

**Issue by Alexsmile2010** [andreipitis/ASPVideoPlayer#11]
How can I Play video from youtube link?

**Comment by andreipitis** [comment]
Hi @Alexsmile2010. 

Unfortunately there is no way to play a YouTube video using `ASPVideoPlayer`, or any other component that uses an `AVPlayer` instance behind the scenes, since the YouTube link is not actually to the video itself, but to a page that has the video embedded.

You can find the official way to play a YouTube video [here](https://developers.google.com/youtube/v3/guides/ios_youtube_helper).
