### ISSUE TITLE
ASPVideoPlayer has no sounds when play video

### ISSUE THREAD

**Issue by onusvishal** [andreipitis/ASPVideoPlayer#41]
Video play but no sound , i add earphone sound is on in earphones.

**Comment by onusvishal** [comment]
Video play but no sound , i add earphone sound is on in earphones.

**Comment by idrisyildiz7** [comment]
Have the same issue, video does not play sound!!?

**Comment by andreipitis** [comment]
Hi @onusvishal, @idrisyildiz7 ,

Since you are hearing audio when you connect your earphones, I am assuming the mute switch on your iPhones was active while using `ASPVideoPlayer`. If you unmute your phones the sound should play as expected.
If you wish to have audio playback even when the mute switch is on, add the following code to your app:
```Swift
do {
 try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playback, mode: AVAudioSession.Mode.moviePlayback)
 try AVAudioSession.sharedInstance().setActive(true)
} catch {
 print(error)
}
```

**Comment by usamabinattique** [comment]
Does not play sound. 
- Mute button is off
- Audio on other apps is working. 
- Can not hear sound from any of the speaker.

**Comment by andreipitis** [comment]
Hi @usamabinattique ,

I can not reproduce your issue, could you provide a sample app?

**Comment by usamabinattique** [comment]
Hello @andreipitis 
No need to reproduce, there was problem in video which was being generated at the backend server. Audio is playing perfectly. 
Thanks for the response, great library and community work.
